package com.example.nelo.util

object Genres {
    val items = mapOf(
        "Action" to 2,
        "Adult" to 3,
        "Adventure" to 4,
        "Comedy" to 6,
        "Cooking" to 7,
        "Doujinshi" to 9,
        "Drama" to 10,
        "Ecchi" to 11,
        "Erotica" to 48,
        "Fantasy" to 12,
        "Gender bender" to 13,
        "Harem" to 14,
        "Historical" to 15,
        "Horror" to 16,
        "Isekai" to 45,
        "Josei" to 17,
        "Manhua" to 44,
        "Manhwa" to 43,
        "Martial arts" to 19,
        "Mature" to 20,
        "Mecha" to 21,
        "Medical" to 22,
        "Mystery" to 24,
        "One shot" to 25,
        "Pornographic" to 47,
        "Psychological" to 26,
        "Romance" to 27,
        "School life" to 28,
        "Sci fi" to 29,
        "Seinen" to 30,
        "Shoujo" to 31,
        "Shoujo ai" to 32,
        "Shounen" to 33,
        "Shounen ai" to 34,
        "Slice of life" to 35,
        "Smut" to 36,
        "Sports" to 37,
        "Supernatural" to 38,
        "Tragedy" to 39,
        "Webtoons" to 40,
        "Yaoi" to 41,
        "Yuri" to 42
    )
}